# Generated by Django 6.1.1 on 2026-09-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empréstimo',
            old_name='dataDevolução',
            new_name='dataDevolucao',
        ),
    ]
