# Generated by Django 6.1.1 on 2026-09-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_datadevolução_empréstimo_datadevolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empréstimo',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
