# Generated by Django 6.1.1 on 2026-09-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empréstimo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empréstimo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
